### ISSUE TITLE
please add filter / library in requirement.txt or cargo.toml

### ISSUE THREAD

**Issue by laticoda** [AndreMiras/gitpop2#5]
Hi, i love your work ! +1 star !
One super feature i would like so much : 
**Add a filter** to target forks which include **library** in their requirement.txt or cargo.toml
Example: i'm looking for ggez's forks with Legion and / or Rayon , on rust Language. 
is it possible ?

**Comment by AndreMiras** [comment]
Hi @laticoda thanks for your support.
I don't think the GitHub REST API or even the GraphQL one would allow such specific query.
Also I feel like it's a bit too specific for being implement in GitPop.
By the way I'm working a new version that's frontend only and rely on the GraphQL API.
https://github.com/AndreMiras/gitpop3
It still misses some basic features, but it's already working OK and run fully on GitHub pages
